(define (problem test1)
(:domain breadMachine)
(:objects a b c d)
(:init (enoughWater)
        (enoughButter)
        (enoughFlour)
        (enoughYeast)
        (enoughSalt)
        )
(:goal (and  (SimpleBread a) (seedBread b) (sweetBread c) (sweetBread2 d)))
)